name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            ext: .exe
          - os: ubuntu-latest  
            name: linux
            ext: ""
          - os: macos-latest
            name: macos
            ext: ""
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: |
        uv add flet Pillow reportlab PyYAML pyinstaller
    
    - name: Build executable
      run: |
        uv run pyinstaller --onefile --windowed --name "ImageToPDFProcessor" main.py
    
    - name: Rename executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        move dist/ImageToPDFProcessor.exe dist/ImageToPDFProcessor-${{ matrix.name }}.exe
    
    - name: Rename executable (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        mv dist/ImageToPDFProcessor dist/ImageToPDFProcessor-${{ matrix.name }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ImageToPDFProcessor-${{ matrix.name }}
        path: dist/ImageToPDFProcessor-${{ matrix.name }}${{ matrix.ext }}
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Image to PDF Processor ${{ github.ref_name }}
        body: |
          ## Image to PDF Processor ${{ github.ref_name }}
          
          ### Downloads
          - **Windows**: `ImageToPDFProcessor-windows.exe`
          - **Linux**: `ImageToPDFProcessor-linux`
          - **macOS**: `ImageToPDFProcessor-macos`
          
          ### Features
          - Convert images to PDFs
          - Annotate existing PDFs with community information
          - Manage community data
          - Cross-platform support
        files: |
          ./artifacts/ImageToPDFProcessor-windows/ImageToPDFProcessor-windows.exe
          ./artifacts/ImageToPDFProcessor-linux/ImageToPDFProcessor-linux
          ./artifacts/ImageToPDFProcessor-macos/ImageToPDFProcessor-macos
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}