name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
    
    - name: Install dependencies
      run: uv sync
    
    - name: Build executable
      run: |
        uv add pyinstaller
        uv run pyinstaller --onefile --windowed --name "ImageToPDFProcessor-${{ matrix.os }}" main.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables-${{ matrix.os }}
        path: dist/
